<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Wildlife;
use Faker\Factory as Faker;

class WildlifeSeeder extends Seeder
{
    public function run(): void
    {
        $species = [
            'African Elephant',
            'Bengal Tiger',
            'Indian Leopard',
            'Indian Cobra',
            'Asiatic Lion',
            'Snow Leopard',
            'Sloth Bear',
            'Red Panda',
            'Great Indian Bustard',
            'Indian Star Tortoise',
            'Gaur',
            'Nilgai',
            'Sambar Deer',
            'Chinkara',
            'Blackbuck',
            'Striped Hyena',
            'Dhole (Indian Wild Dog)',
            'Indian Pangolin',
            'Indian Fox',
            'Golden Jackal',
            'Wild Boar',
            'Indian Bison',
            'Barasingha',
            'Indian Peafowl',
            'Sarus Crane',
            'King Cobra',
            'Indian Rock Python',
            'Gharial',
            'Mugger Crocodile',
            'Olive Ridley Turtle',
            'Indian Scops Owl',
            'Indian Eagle Owl',
            'Indian Roller',
            'Common Myna',
            'Green Bee-eater',
            'Rufous Treepie',
            'Indian Paradise Flycatcher',
            'Hornbill',
            'Malabar Civet',
            'Lion-tailed Macaque',
            'Bonnet Macaque',
            'Assam Macaque',
            'Hoolock Gibbon',
            'Himalayan Monal',
            'Indian Vulture',
            'White-rumped Vulture',
            'Indian Krait',
            'Russell’s Viper',
            'Saw-scaled Viper',
            'Monitor Lizard',
            'Indian Chameleon',
            'Common Kestrel',
            'Eurasian Sparrowhawk',
            'Black Kite',
            'Shikra',
            'Indian Grey Hornbill',
            'Indian Cuckoo',
            'Koel',
            'Jungle Babbler',
            'Red-vented Bulbul',
            'Crested Serpent Eagle',
            'Pied Kingfisher',
            'White-throated Kingfisher',
            'Common Kingfisher',
            'Asian Koel',
            'Blue Jay',
            'Painted Stork',
            'Openbill Stork',
            'Woolly-necked Stork',
            'Black-necked Stork',
            'Greater Flamingo',
            'Lesser Flamingo',
            'Spot-billed Pelican',
            'Comb Duck',
            'Ruddy Shelduck',
            'Northern Pintail',
            'Gadwall',
            'Indian Spot-billed Duck',
            'Bar-headed Goose',
            'Greylag Goose',
            'Marsh Harrier',
            'Indian Cormorant',
            'Little Cormorant',
            'Indian Pond Heron',
            'Cattle Egret',
            'Little Egret',
            'Great Egret',
            'Grey Heron',
            'Purple Heron',
            'Black-headed Ibis',
            'Glossy Ibis',
            'Indian Skimmer',
            'River Tern',
            'Black-bellied Tern',
            'Whiskered Tern',
            'Brown Fish Owl',
            'Jungle Owlet',
            'Spotted Owlet',
            'Barn Owl',
            'Oriental Scops Owl'
        ];

        foreach ($species as $index => $animal) {
            Wildlife::create([
                'name' => $animal,
                'species' => explode(' ', $animal)[1] ?? $animal,
                'habitat' => ['Forest', 'Wetlands', 'Grassland', 'Mountains'][rand(0, 3)],
                'description' => $animal . ' is a species commonly found in Indian subcontinent.'
            ]);
        }
    }
}